name = "xtranumerik-website"
compatibility_date = "2025-08-26"

[env.production]
compatibility_date = "2025-08-26"

# Configuration pour site statique avec assets
[assets]
directory = "."
exclude = ["*.md", "*.log", ".git/*", "node_modules/*", "wrangler.toml"]

# Variables d'environnement
[vars]
ENVIRONMENT = "production"

# Configuration de routage personnalisé
[[route]]
pattern = "xtranumerik.ca/*"
zone_name = "xtranumerik.ca"

# Headers de sécurité et performance
[[headers]]
name = "X-Frame-Options"
value = "DENY"

[[headers]]  
name = "X-Content-Type-Options"
value = "nosniff"

[[headers]]
name = "Strict-Transport-Security" 
value = "max-age=31536000; includeSubDomains; preload"

# Configuration spéciale pour les assets
[[assets.bindings]]
name = "ASSETS"
type = "assets"
